version: "3.6"
services:
  backend:
    container_name: learn_api
    build:
      dockerfile: Dockerfile
      context: .
      args:
        USER: fastapi
        UID: 1000
        GID: 1000
    depends_on:
      - database
    ports:
      - "8000:80"
    volumes:
      - ".:/run"
    working_dir: /run
    tty: true
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--port", "80", "src.main:app", "--reload"]
  database:
    image: postgres
    container_name: learn_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5437:5432"
volumes:
  postgres-data:
    name: "learn_postgres"
